name: CommandFilter
main: com.pb.commandfilter.CommandFilter
version: 1.11
api-version: 1.13
commands:
   commandfilter:
      description: Adds a filter for command or modifies a configuration.
      usage: "/<command>  add|remove  target  regex OR /<command>  config  key  value"
      permission: commandfilter.modifyconfig
   chatfilter:
      description: Adds a filter for chat messages.
      usage: "/<command>  add|remove  target  regex"
      permission: commandfilter.modifyconfig